version: '3.4'

services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0.8-alpine
    restart: always
    volumes:
      - ./data/redis-data:/data
    ports:
      - "6379:6379"

  whatsapp_api:
    build:
      context: ./packages/service-wa-bot
      target: development
    depends_on: [ postgres, redis ]
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./data/packages/service-wa-bot:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WEBHOOK_ENABLED=true
      - WEBHOOK_URL=https://yourdomain.com/api/v1/webhook
      - WEBHOOK_BASE64=true
      - PROTECT_ROUTES=true
      - MARK_MESSAGES_READ=true
      - WEBHOOK_ALLOWED_EVENTS=all
      - DB_HOST=localhost
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    restart: always
    command: npm run dev

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # Enable health and metrics support
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      # Configure a database vendor
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=johndoe
      - KC_DB_PASSWORD=randompassword
       
    depends_on:
      postgres:
        condition: service_healthy


